<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="8.0.11" />
    <PackageReference Include="Testcontainers.PostgreSql" Version="3.10.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="NSubstitute" Version="5.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\BuildingBlocks\Infrastructure\BuildingBlocks.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Host\CrmErp.Host\CrmErp.Host.csproj" />
    <ProjectReference Include="..\..\src\Modules\CRM\Domain\Modules.CRM.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\CRM\Application\Modules.CRM.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\CRM\Infrastructure\Modules.CRM.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Customer\Domain\Modules.Customer.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Customer\Application\Modules.Customer.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Customer\Infrastructure\Modules.Customer.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Sales\Domain\Modules.Sales.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Sales\Application\Modules.Sales.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Sales\Infrastructure\Modules.Sales.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Project\Domain\Modules.Project.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Project\Application\Modules.Project.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Project\Infrastructure\Modules.Project.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Finance\Domain\Modules.Finance.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Finance\Application\Modules.Finance.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Finance\Infrastructure\Modules.Finance.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Support\Domain\Modules.Support.Domain.csproj" />
    <ProjectReference Include="..\..\src\Modules\Support\Application\Modules.Support.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Support\Infrastructure\Modules.Support.Infrastructure.csproj" />
  </ItemGroup>

</Project>
